---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.16.0
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    worker:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
      config:
        core:
          sources: ["custom", "pci", "usb", "system"]
        sources:
          usb:
            deviceClassWhitelist: ["02", "03", "0e", "ef", "fe", "ff"]
            deviceLabelFields: ["class", "vendor", "device"]
    master:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: "node-role.kubernetes.io/control-plane"
                    operator: In
                    values: [""]

    gc:
      resources:
        limits:
          cpu: 200m
          memory: 1Gi
