---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: snapshot-controller
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    controller:
      volumeSnapshotClasses:
        - name: longhorn-snapclass
          annotations:
            snapshot.storage.kubernetes.io/is-default-class: "true"
          driver: driver.longhorn.io
          deletionPolicy: Delete
          parameters:
            type: snap  # a CSI snapshot maps to a Longhorn snapshot
      serviceMonitor:
        create: true
    webhook:
      enabled: false
