---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name pihole-exporter-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PIHOLE_PASSWORD: "{{ .pass }}"
  dataFrom:
    - extract:
        key: pihole
