---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pihole-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ekofr/pihole-exporter
              tag: v0.4.0
            env:
              PIHOLE_HOSTNAME: 192.168.186
              PORT: 9617
            envFrom:
              - secretRef:
                  name: pihole-exporter-secret
            resources:
              requests:
                cpu: 15m
                memory: 30M
              limits:
                memory: 256M
    service:
      main:
        ports:
          http:
            enabled: false
          metrics:
            enabled: true
            protocol: TCP
            port: 9617
    serviceMonitor:
      main:
        enabled: true
        endpoints:
        - port: metrics
          scheme: http
          path: /metrics
          interval: 30m
          scrapeTimeout: 1m
