---
apiVersion: batch/v1
kind: Job
metadata:
  name: a6
  namespace: default
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      nodeName: nuc13i7-4
      containers:
        - name: main
          image: docker.io/library/alpine:latest
          command: ["/bin/sh", "-c"]
          args: ["rm -rf /mnt/host_var/lib/rook"]
          volumeMounts:
            - mountPath: /mnt/host_var
              name: host-var
          securityContext:
            privileged: true
          resources: {}
      volumes:
        - name: host-var
          hostPath:
            path: /var
