---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name external-dns-unifi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        UNIFI_USER: "{{ .UNIFI_USER }}"
        UNIFI_PASS: "{{ .UNIFI_PASS }}"
  dataFrom:
    - extract:
        key: unifi
