---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi-dns
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: unifi-dns
  install:
    disableSchemaValidation: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    disableSchemaValidation: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/kashalls/external-dns-unifi-webhook
          tag: v0.5.1@sha256:fc031337a83e3a7d5f3407c931373455fe6842e085b47e4bb1e73708cb054b06
        env:
          - name: LOG_LEVEL
            value: "debug"
          - name: UNIFI_HOST
            value: "https://192.168.1.1"
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: UNIFI_USER
            valueFrom:
              secretKeyRef:
                name: &secret external-dns-unifi
                key: UNIFI_USER
          - name: UNIFI_API_KEY
            valueFrom:
              secretKeyRef:
                name: *secret
                key: UNIFI_API_KEY
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    extraArgs:
      - --ingress-class=internal
    policy: sync
    txtOwnerId: main
    txtPrefix: k8s.
    sources:
      - ingress
      - service
    domainFilters:
      - "${SECRET_DOMAIN}"
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
