---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: overseerr
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      overseerr:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          overseerr:
            image:
              repository: ghcr.io/sct/overseerr
              tag: 1.33.2
            env:
              TZ: "America/New_York"
              LOG_LEVEL: "info"

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      overseerr:
        controller: overseerr
        ports:
          http:
            port: 5055

    ingress:
      overseerr:
        enabled: true
        className: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "request.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: overseerr
                  port: http
        tls:
          - hosts:
              - *host
            secretName: overseer.tls

    resources:
      requests:
        cpu: 15m
        memory: 291M
      limits:
        cpu: 500m
        memory: 4Gi

    persistence:
      config:
        existingClaim: overseerr
        globalMounts:
          - path: /app/config
