---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name external-dns-bind
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RNDC_KEY: "{{ .rdnc }}"
  dataFrom:
    - extract:
        key: bind
