---
originRequest:
  http2Origin: true

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: https://nginx-external-controller.networking.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN}"
    service: https://nginx-external-controller.networking.svc.cluster.local:443
  - hostname: "${SECRET_DOMAIN2}"
    service: https://nginx-external-controller.networking.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN2}"
    service: https://nginx-external-controller.networking.svc.cluster.local:443
  - service: http_status:404
