---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: zooz-zwave-device
spec:
  rules:
    - # Zooz 700 Z-Stick
      name: zooz700.zwave
      labels:
        zooz.feature.node.kubernetes.io/zwave: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            class: { op: In, value: ["ff"] }
            vendor: { op: In, value: ["10c4"] }
            device: { op: In, value: ["ea60"] }
