---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-cache
  namespace: media
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn
