---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name sonarr-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SONARR__AUTH__APIKEY: "{{ .sonarr_api_key }}"
        SONARR__POSTGRES__HOST: &dbHost "{{ .postgres_db_host }}"
        SONARR__POSTGRES__PORT: "5432"
        SONARR__POSTGRES__USER: &dbUser "{{ .sonarr_postgres_user }}"
        SONARR__POSTGRES__PASSWORD: &dbPass "{{ .sonarr_postgres_pass }}"
        SONARR__POSTGRES__MAINDB: sonarr4k_main
        SONARR__POSTGRES__LOGDB: sonarr4k_log
        INIT_POSTGRES_DBNAME: sonarr4k_main sonarr4k_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .pgpassword }}"
        NAS1_ADDR: "{{ .nas1_addr }}"
        NAS2_ADDR: "{{ .nas2_addr }}"
        NAS3_ADDR: "{{ .nas3_addr }}"
        NAS4_ADDR: "{{ .nas4_addr }}"
        # PUSHOVER_TOKEN: "{{ .SONARR_PUSHOVER_TOKEN }}"
        # PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: sonarr4k
    - extract:
        key: nas-info
    - extract:
        key: pushover
