---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sonarr4k
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 65539

    controllers:
      sonarr4k:

        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: sonarr4k
        containers:
          sonarr4k:
            image:
              repository: ghcr.io/onedr0p/sonarr-develop
              tag: 4.0.13.2931@sha256:2cc6fececf50f6ec4be24ec15dea611261833904f322bbd5e51b6379cbbadf57
            env:
              TZ: "${TIMEZONE}"
              SONARR__APP__INSTANCENAME: Sonarr
              SONARR__SERVER__PORT: &port 8989
              SONARR__LOG__LEVEL: info
              SONARR__APP__THEME: dark
              SONARR__UPDATE__BRANCH: develop
            envFrom: *envFrom
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    service:
      sonarr4k:
        controller: sonarr4k
        ports:
          http:
            port: *port

    ingress:
      sonarr4k:
        enabled: true
        className: internal
        hosts:
          - host: &host "sonarr4k.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: sonarr
                  port: http
        tls:
          - hosts:
              - *host
            secretName: sonarr4k.tls

    persistence:
      config:
        existingClaim: *app

      # pushover-notify:
      #   type: configMap
      #   name: sonarr-configmap
      #   defaultMode: 0775
      #   globalMounts:
      #     - path: /scripts/pushover-notify.sh
      #       subPath: pushover-notify.sh
      #       readOnly: true

      media:
        type: nfs
        path: /volume1/Media
        globalMounts:
          - path: /media

      media2:
        type: nfs
        path: /volume1/Media2
        globalMounts:
          - path: /media2

      media3:
        type: nfs
        path: /volume1/Media
        globalMounts:
          - path: /media3

      temp:
        type: nfs
        path: /volume1/temp
        globalMounts:
          - path: /temp_dir

  valuesFrom:
    - kind: Secret
      name: *app
      valuesKey: NAS1_ADDR
      targetPath: persistence.media.server

    - kind: Secret
      name: *app
      valuesKey: NAS1_ADDR
      targetPath: persistence.temp.server

    - kind: Secret
      name: *app
      valuesKey: NAS2_ADDR
      targetPath: persistence.media2.server

    - kind: Secret
      name: *app
      valuesKey: NAS3_ADDR
      targetPath: persistence.media3.server
