---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name thanos-bucket
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .minio_user }}"
        AWS_SECRET_ACCESS_KEY: "{{ .minio_pass }}"
        BUCKET_NAME: "{{ .thanos_bucket }}"
        BUCKET_HOST: "{{ .thanos_bucket_endpoint }}"
        S3_REGION: us-east-1
  dataFrom:
    - extract:
        key: volsync-minio
    - extract:
        key: thanos
