---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly1
spec:
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.15.1
  replicas: 3
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: dragonfly-bkup
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: dragonfly-bkup
          key: AWS_SECRET_ACCESS_KEY
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1280Mi
  args:
    - "--maxmemory=1128Mi"
    - "--proactor_threads=4"
    - "--cluster_mode=emulated"
