---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dragonfly-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dragonfly-bkup
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .minio_user }}"
        AWS_SECRET_ACCESS_KEY: "{{ .minio_pass }}"
  dataFrom:
    - extract:
        key: volsync-minio