---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name jellyfin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NAS1_ADDR: "{{ .nas1_addr }}"
        NAS2_ADDR: "{{ .nas2_addr }}"
        NAS3_ADDR: "{{ .nas3_addr }}"
  dataFrom:
    - extract:
        key: nas-info
