---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name external-dns-pihole
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        EXTERNAL_DNS_PIHOLE_SERVER: "{{ .pihole_addr }}"
        EXTERNAL_DNS_PIHOLE_PASSWORD: "{{ .pass }}"
        EXTERNAL_DNS_PIHOLE_TLS_SKIP_VERIFY: "true"
  dataFrom:
    - extract:
        key: pihole
