---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.14.4
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: pihole
    envFrom:
      - secretRef:
          name: &secret external-dns-pihole
    extraArgs:
      - --ingress-class=internal
    policy: upsert-only
    registry: noop
    sources:
      - ingress
    domainFilters:
      - "${SECRET_DOMAIN}"
      - "${SECRET_DOMAIN2}"
      - "${SECRET_DOMAIN3}"
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret