---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-api-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudflare
        property: CLOUDFLARE_APITOKEN
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name issuers-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CLOUDFLARE_APITOKEN: "{{ .issuer_token }}"
  dataFrom:
    - extract:
        key: cert-manager
