---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name bazarr-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bazarr
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Bazarr postgres variables
        POSTGRES_ENABLED: "true"
        POSTGRES_HOST: &dbHost "{{ .postgres_db_host }}"
        POSTGRES_PORT: "5432"
        POSTGRES_USERNAME: &dbUser "{{ .bazarr_db_user }}"
        POSTGRES_PASSWORD: &dbPass "{{ .bazarr_db_pass }}"
        POSTGRES_DATABASE: &dbName bazarr
        # Init database vars
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .pgusername }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .pgpassword }}"
        NAS1_ADDR: "{{ .nas1_addr }}"
        NAS2_ADDR: "{{ .nas2_addr }}"
        NAS3_ADDR: "{{ .nas3_addr }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: bazarr
    - extract:
        key: nas-info
