---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bazarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 65539

    controllers:

      bazarr:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.3
            envFrom: &envFrom
              - secretRef:
                  name: bazarr

        containers:
          bazarr:
            image:
              repository: ghcr.io/onedr0p/bazarr
              tag: 1.4.2@sha256:7f152a7b8f46707f5feb68a315d8989cb85ed9e8b6868608f80e6f5eb6cc2e8e

            env:
              TZ: "${TIMEZONE}"
            envFrom: *envFrom

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    ingress:
      bazarr:
        enabled: false
        className: "nginx"
        hosts:
          - host: &host "bazarr.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: bazarr
                  port: http
        tls:
          - hosts:
              - *host
            secretName: bazarr.tls

    service:
      bazarr:
        controller: bazarr
        ports:
          http:
            port: 6767

    persistence:
      config:
        existingClaim: *app

      media:
        type: nfs
        path: /volume1/Media
        globalMounts:
          - path: /media

      media2:
        type: nfs
        path: /volume1/Media2
        globalMounts:
          - path: /media2

      media3:
        type: nfs
        path: /volume1/Media
        globalMounts:
          - path: /media3

      temp:
        type: nfs
        path: /volume1/temp
        globalMounts:
          - path: /temp_dir

  valuesFrom:
    - kind: Secret
      name: *app
      valuesKey: NAS1_ADDR
      targetPath: persistence.media.server

    - kind: Secret
      name: *app
      valuesKey: NAS1_ADDR
      targetPath: persistence.temp.server

    - kind: Secret
      name: *app
      valuesKey: NAS2_ADDR
      targetPath: persistence.media2.server

    - kind: Secret
      name: *app
      valuesKey: NAS3_ADDR
      targetPath: persistence.media3.server
