---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      version: 1.14.3
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    interval: 5m
    logLevel: debug
    provider: cloudflare
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: external-dns
            key: email
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns
            key: token
    extraArgs:
      - --cloudflare-proxied
      - --annotation-filter=external-dns/is-public in (true)
      - --aws-prefer-cname
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
    policy: sync
    sources:
      - ingress
      - service
      - crd
    txtPrefix: "k8s."
    txtOwnerId: "default"
    domainFilters:
      - "${SECRET_DOMAIN}"
      - "${SECRET_DOMAIN2}"
      - "${SECRET_DOMAIN3}"
    resources:
      requests:
        memory: 105M
        cpu: 15m
