---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app prowlarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 65539

    controllers:
      prowlarr:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: *app

        containers:
          prowlarr:
            image:
              repository: ghcr.io/onedr0p/prowlarr-nightly
              tag: 1.16.0.4401
            env:
              COMPlus_EnableDiagnostics: "0"
              PROWLARR__INSTANCE_NAME: Prowlarr
              TZ: "America/New_York"
              PROWLARR__AUTHENTICATION_METHOD: External
              PROWLARR__PORT: &port 9696
              PROWLARR__THEME: dark
              PROWLARR__LOG_LEVEL: info
            envFrom: *envFrom
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    service:
      prowlarr:
        controller: prowlarr
        ports:
          http:
            port: 9696

    ingress:
      prowlarr:
        enabled: false
        className: "nginx"
        hosts:
          - host: &host "prowlarr.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: prowlarr
                  port: http
        tls:
          - hosts:
              - *host
            secretName: prowlarr.tls

    persistence:
      config:
        type: emptyDir
      tmp:
        type: emptyDir
