---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app opnsense
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      opnsense:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "@daily"
        containers:
          app:
            image:
              repository: ghcr.io/drag0n141/kubernetes-kubectl
              tag: 1.31.2@sha256:beddf23637b6db3b4b5000ea0ee85bf34ae1fc1a265d4fd0b9fb004eeaf2699c
            command: ["/bin/bash", "/app/opnsense-backup.sh"]
            envFrom:
              - secretRef:
                  name: opnsense-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
    persistence:
      script:
        type: configMap
        name: opnsense-backup
        defaultMode: 0775
        globalMounts:
          - path: /app/opnsense-backup.sh
            subPath: opnsense-backup.sh
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
