---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  maxHistory: 3
  interval: 30m
  suspend: false
  releaseName: ingress-nginx
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.10.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controller:
      admissionWebhooks:
        enabled: false
        timeoutSeconds: 30
      extraEnvs:
        - name: TZ
          value: "${TIMEZONE}"
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "ingress.${SECRET_DOMAIN}"
          io.cilium/lb-ipam-ips: "192.168.10.40"
        loadBalancerIP: "192.168.10.40"
        externalTrafficPolicy: Cluster
      publishService:
        enabled: true
      ingressClassResource:
        default: true
      config:
        client-body-buffer-size: 100M
        client-body-timeout: 120
        client-header-timeout: 120
        enable-brotli: "true"
        enable-real-ip: "true"
        hsts-max-age: 31449600
        keep-alive-requests: 10000
        keep-alive: 120
        proxy-body-size: 0
        proxy-buffer-size: 16k
        ssl-protocols: TLSv1.3 TLSv1.2
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: networking
          namespaceSelector:
            any: true
      resources:
        requests:
          cpu: 10m
          memory: 250Mi
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.27.0
      extraEnvs:
        - { name: TEMPLATE_NAME, value: lost-in-space }
        - { name: SHOW_DETAILS, value: "false" }
