---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sabnzbd
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m

  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: volsync-system
  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 65539

    controllers:
      sabnzbd:

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          sabnzbd:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.4.1@sha256:b7380cd5a93a0a232c5ce25803531b1575453953e99de4e6b8a1398e73442e5b
            env:
              TZ: "America/New_York"
              SABNZBD__PORT: &port 8080

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    service:
      sabnzbd:
        controller: *app
        ports:
          http:
            port: *port

    ingress:
      sabnzbd:
        enabled: false
        className: "nginx"
        hosts:
          - host: &host "sabnzbd.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: sabnzbd
                  port: http
        tls:
          - hosts:
              - *host
            secretName: sabnzbd.tls


    persistence:

      config:
        enabled: true
        existingClaim: *app

      downloads:
        enabled: true
        existingClaim: sabnzbd-downloads-v1
        globalMounts:
          - path: /downloads

      temp:
        type: nfs
        path: /volume1/temp
        globalMounts:
          - path: /temp_dir

      temp4k:
        type: nfs
        path: /mnt/volume01/sabnzbd4k
        globalMounts:
          - path: temp_dir4k

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 16384Mi

  valuesFrom:
    - kind: Secret
      name: *app
      valuesKey: NAS1_ADDR
      targetPath: persistence.temp.server
    - kind: Secret
      name: *app
      valuesKey: NAS4_ADDR
      targetPath: persistence.temp4k.server
