---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
spec:
  interval: 30m
  chart:
    spec:
      chart: kubelet-csr-approver
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: postfinance
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    providerRegex: ^(nuc11i7-1|nuc10i7-1|nuc10i7-2|nuc11i7-2|nuc13i7-1|nuc13i7-2|nuc13i7-3|nuc13i7-4)$
    bypassDnsResolution: true
    metrics:
      enable: true
      serviceMonitor:
        enabled: true
