---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 65539

    controllers:
      sonarr:

        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: sonarr
        containers:
          sonarr:
            image:
              repository: ghcr.io/onedr0p/sonarr-develop
              tag: 4.0.4.1515@sha256:77a9c8cd3911f3bddbf89b47fe8ad939fac2a1cf587833b5a43eca1b8f58e249
            env:
              TZ: "${TIMEZONE}"
              SONARR__INSTANCE_NAME: Sonarr
              SONARR__PORT: &port 8989
              SONARR__LOG_LEVEL: info
            envFrom: *envFrom
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    service:
      sonarr:
        controller: sonarr
        ports:
          http:
            port: *port

    ingress:
      sonarr:
        enabled: false
        className: internal
        hosts:
          - host: &host "sonarr.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: sonarr
                  port: http
        tls:
          - hosts:
              - *host
            secretName: sonarr.tls

    persistence:
      config:
        existingClaim: *app

      media:
        type: nfs
        path: /volume1/Media
        globalMounts:
          - path: /media

      media2:
        type: nfs
        path: /volume1/Media2
        globalMounts:
          - path: /media2

      media3:
        type: nfs
        path: /volume1/Media
        globalMounts:
          - path: /media3

      temp:
        type: nfs
        path: /volume1/temp
        globalMounts:
          - path: /temp_dir

  valuesFrom:
    - kind: Secret
      name: *app
      valuesKey: NAS1_ADDR
      targetPath: persistence.media.server

    - kind: Secret
      name: *app
      valuesKey: NAS1_ADDR
      targetPath: persistence.temp.server

    - kind: Secret
      name: *app
      valuesKey: NAS2_ADDR
      targetPath: persistence.media2.server

    - kind: Secret
      name: *app
      valuesKey: NAS3_ADDR
      targetPath: persistence.media3.server
