---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./../../../../templates/volsync
  - ./externalsecrets.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: sonarr-configmap
    files:
      - pushover-notify.sh=./resources/pushover-notify.sh
