---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name radarr-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RADARR__API_KEY: "{{ .radarr_api_key }}"
        RADARR__POSTGRES_HOST: &dbHost "{{ .postgres_db_host }}"
        RADARR__POSTGRES_PORT: "5432"
        RADARR__POSTGRES_USER: &dbUser "{{ .radarr_postgres_user }}"
        RADARR__POSTGRES_PASSWORD: &dbPass "{{ .radarr_postgres_pass }}"
        RADARR__POSTGRES_MAIN_DB: radarr_main
        RADARR__POSTGRES_LOG_DB: radarr_log
        INIT_POSTGRES_DBNAME: radarr_main radarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .pgpassword }}"
        NAS1_ADDR: "{{ .nas1_addr }}"
        NAS2_ADDR: "{{ .nas2_addr }}"
        NAS3_ADDR: "{{ .nas3_addr }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: radarr
    - extract:
        key: nas-info
