---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 65539

    controllers:
      radarr:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.3
            envFrom: &envFrom
              - secretRef:
                  name: radarr

        containers:
          radarr:
            image:
              repository: ghcr.io/onedr0p/radarr-develop
              tag: 5.12.2.9335@sha256:6c4dc76eddeb06cb362ce46ac4a4beed64c49126caed70bf4d21eb8c86f70249

            env:
              TZ: "${TIMEZONE}"
              RADARR__PORT: &port 7878
              RADARR__AUTHENTICATION_METHOD: External
            envFrom: *envFrom

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    service:
      radarr:
        controller: radarr
        ports:
          http:
            port: *port

    ingress:
      radarr:
        enabled: false
        className: "nginx"
        hosts:
          - host: &host "radarr.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: radarr
                  port: http
        tls:
          - hosts:
              - *host
            secretName: radarr.tls

    persistence:
      config:
        existingClaim: *app

      media:
        type: nfs
        path: /volume1/Media
        globalMounts:
          - path: /media

      temp:
        type: nfs
        path: /volume1/temp
        globalMounts:
          - path: /temp_dir

  valuesFrom:
    - kind: Secret
      name: *app
      valuesKey: NAS1_ADDR
      targetPath: persistence.media.server

    - kind: Secret
      name: *app
      valuesKey: NAS1_ADDR
      targetPath: persistence.temp.server
