---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capacitor
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      capacitor:
        strategy: RollingUpdate
        containers:
          capacitor:
            image:
              repository: ghcr.io/gimlet-io/capacitor
              tag: v0.4.2
              pullPolicy: Always
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
                ephemeral-storage: 1Gi
              limits:
                memory: 200Mi
                ephemeral-storage: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    serviceAccount:
      create: true
      name: "capacitor"
    service:
      capacitor:
        controller: capacitor
        ports:
          http:
            enabled: true
            port: 9000
    ingress:
      capacitor:
        className: nginx
        enabled: false
        hosts:
          - host: &host capacitor.${INTERNAL_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: capacitor
                  port: http
        tls:
          - hosts:
              - *host
            secretName: capacitor-internal.tls
