apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:GEd2LrckVSRthliOUVIEDYhs,iv:rKg+qiVY9pQrfEseBVHN27nXQrl2+wVcRxD/jRscOqM=,tag:0s15vIheAPN78DPXcpCPVQ==,type:str]
    SVC_CNPG_ADDR: ENC[AES256_GCM,data:nbVMK5C9U4vxvsKzcQ==,iv:gG/qeq+lhsfa3jf7woecnFVtZvHkBrfuCm5yFqkYDI0=,tag:UoSensZrkNjOMx7P5YwZAA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:bOem2iOBkb1jwphMwnk=,iv:QF+654wMurvGFB5tcDoBVpQsINXH0kCZpfY4ql08Wg8=,tag:GHZdJlY5YkPcYfZ/HMBPwA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:aVvlgYhIGZHXuy6uKY8J9mTl,iv:ijJ25M/5lwGIYzkJaajX0YGxzjYawpRQk+K/2PgGtnk=,tag:8MWObK5/IZCVSYmq2PxZdA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:J1kA58kHBaDnJV7LSTFw3sxcYBUpelvmpIAaMu2yZArNpFhK,iv:bMHXhPXiUBj9Vv3Z9cRtKZf8iew+A3MCqCGMAx54vXQ=,tag:3CcgerLdef30r2yu/nteIw==,type:str]
    SECRET_TZ: ENC[AES256_GCM,data:hQBhsyfb5rPzhbKK92bltg==,iv:P5qo2MqFxKlgps9GwxMofg3pfnlnkiREhefqjyA+KnE=,tag:TJamc5JNO2W866nX2JReEA==,type:str]
    SECRET_VPN_FORWARDED_PORT_1: ENC[AES256_GCM,data:zsLMf+4=,iv:bXRW71K8TW2oO9Afgwp11iBAOMBPoP0UHhnYWuVzZ/E=,tag:HbEhosmNo6m5kPwoSaVQHw==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:XUoFUjt7o1PA2GZlJBkKfIEs,iv:S6QjGe0aenEwATjb9QnnJ7srC5XTn+zwMlLdNITXI0E=,tag:tdW2xWidTnrQJWtwuhyXog==,type:str]
    IPINFO_TOKEN: ENC[AES256_GCM,data:Kj3QxTjM+qKzWauT4go=,iv:RfMb78cQp5wd+fHWCWB1s54ugO29TX6kCIUvTVWzJDo=,tag:N06skPM6ChEuDM6ZkU547Q==,type:str]
    SECRET_DOMAIN2: ENC[AES256_GCM,data:sVThfEpZ9YkfOXPtaw==,iv:5JfC+WqwvIvc5jGKkaIzpG1351smh3+hnz5OVpmn3AQ=,tag:/36xzUZhJiBewJJu2Q7dag==,type:str]
    SECRET_DOMAIN3: ENC[AES256_GCM,data:QS5KARapFJ9CwzF+OqI=,iv:GifD8yLO2Ws29Sex+czMxCz7AgdzTOSw9agdh3ReK0E=,tag:LJiUbdfMSK7oyoSnGAYRIg==,type:str]
    SECRET_NEXTCLOUD: ENC[AES256_GCM,data:EsbuYXlNPl4KNFFlASbk,iv:u84nSSJ0itblt+x3iBOrwL/XnfupRS5ENmEZPqyxDVE=,tag:vw5czo1FC7CxnxIDTDiKvg==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:VZrJlx9ARNe7BR/hixSZKUiJD64=,iv:uI7/Y+Ma85QzkZ66ZNPnOZ5UY8dgAWtmnOQNLByVZ4w=,tag:hU3FYKT5XcJJX7xBK6UcFg==,type:str]
    VALHEIM_SERVER: ENC[AES256_GCM,data:SdS/Lvs=,iv:NxruwGXDZKbtxh8p+KixjEcxPMdycd3R0WBLSNmMrE4=,tag:sTedmE+I5NB6NwBK0bf6Rg==,type:str]
    VALHEIM_WORLD: ENC[AES256_GCM,data:Rps40TA=,iv:x42doDaxAPBK2b10T8MK7qcN1qRiB5KhKfXRCIqoTZg=,tag:TZknzqKMEODpYG28waW0Dw==,type:str]
    VALHEIM_PASS: ENC[AES256_GCM,data:CQL+afs=,iv:6XyjmawtZuKf04phK9fmabcxjkvHC97N7dDbDNuD5/o=,tag:xLLhVEYzr3ZFzjpmiYddMw==,type:str]
    SUPERVISOR_PASS: ENC[AES256_GCM,data:afRPS286ZkH5,iv:m4jjch1jDBhMQRhrM/FXilTR4gLihxF/r0MU8E62ds0=,tag:GzE3oJOKoXiiAsjigYzRGw==,type:str]
    PLEX_CLAIM: ENC[AES256_GCM,data:5s+97j6INlPz12ckYIbIqZmzfv3WgInplFM=,iv:2MNS8a/ALD6govrb/9o3jketlShpnDdhMonrzlfGP+I=,tag:wtUzJB9Lmw6knjvcRkTwnA==,type:str]
    LOKI_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:ukJN4NXhlbCLHsLSEg==,iv:g4WaxqJMhqYOVoxeJ1aYi8JDyLyTG3/Kdlc2s8MaLqs=,tag:jC2aEoTQfRysPmZPKSTT6g==,type:str]
    LOKI_MINIO_SECRET_KEY: ENC[AES256_GCM,data:eQNx4+txp37TpKfcJA3vqW11D1Yibjns,iv:yhL4opYyQqYVLTROj2CopdcY411PlPT71M0p5Qw42X4=,tag:gFhsQBfq3ENtM37DF4rXMw==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:S3MIda7fe3y9,iv:QInpeh+x8b2O0qnOMTelkDmg707MOw9K9VVB3J/Nzwg=,tag:i/fi1eN91j+p8Imbh/mI5w==,type:str]
    SECRET_POSTGRESQL_KUBE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:t9ZWNEH4/UFq,iv:RrE0lxvTXlQMY/KevKTNQ37yV6SFBvnvSMbjVJsya9s=,tag:tIy1wFZgd2VlRXmZjCTBQg==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:IGTxpNLGSbTt,iv:mDe5ZafibraiTykNnGp3LjZDsUto1RW/8/IPUXGfGa8=,tag:0K+4zsxtd2V7l2FVWTbL7g==,type:str]
    VALHEIM_DISCORD: ENC[AES256_GCM,data:eT26rGZ3yYUKIpHOhEZbMj2Ivo1ErItZ/ub1/tYsaMI8HnCyUHh70jbKgZlh/71rOGBII2HtUg68Y0mSEsjTZV2K6T5bz4SI+dNfOo9bXo5Blux768EykieGJ98XDj7MUUlSKBk/sXnE5kooHsT9p8JeD4Plhh8P,iv:tUQzD1xudUm5guuVTGZjMoQdWI9+tKZA5lpzSlkOQH0=,tag:9X8jp49/lGLtME0HrEb4yQ==,type:str]
    SAM_EMAIL: ENC[AES256_GCM,data:A1/m393uBW9XkcsVleGyYlDwow==,iv:J5XGd0EHNtVjwi83zb1kff8UIXICS0dsE/YHTGKcolI=,tag:qDCCzAL+2uopT7zmc8ESqw==,type:str]
    AUTHENTIK_KEY: ENC[AES256_GCM,data:ujtJ5yzBi2ABHQ2N7FIe22+DHvVDPv+Ktypdb1Cdl4iDwyaLFSLDEilG+ceFPVt4XHA=,iv:4Su2V4gRphEMZZvMTlWxwQ4qB7+ejdSMlESLhxlVJMI=,tag:13izwqT7uHi1FAPwJyglRQ==,type:str]
    ROCKET_DB_ROOT: ENC[AES256_GCM,data:1H+oeJHS+IS/UA==,iv:NM/xME3F91SzlIkWI4RzdF8TfwkIZFeoQaI76GJ2IrQ=,tag:ksgbAOi2cNrLadYP6/cP7Q==,type:str]
    ROCKET_DB_USR: ENC[AES256_GCM,data:YEWHHWGw4NyWeQ==,iv:Y+sQvaf/eCQywRjvqezX9bdc4QvHBcq0ZgEq9BAdHZU=,tag:V0X0YC2rbRrKDCyaqWjoeQ==,type:str]
    ROCKET_DB_PASS: ENC[AES256_GCM,data:sxPKhFU6upe8Cg==,iv:Mir7ZkoPqnYKCKtzHTFNvlQMS7h8To8f5v2Fxvegx18=,tag:bW2AumpE2ZS90m5YFBnqAQ==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:M6EmWRLRtZlwQq1/Lid1aZgCXL7h,iv:2DZY8xtIBks95UmsyZmWqvb9/faFy5oEoEiFayaaZNs=,tag:Cdk1YZDT8yaMcSRz4RN/mA==,type:str]
    SECRET_AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:QxvPw0ObHYSk9qVVGgrGraI4,iv:bBiaIcUZECwImfioWl8ui+Ix+lrA85FwRQMIJeWF/hE=,tag:MmE0UkuH8ArTEePsrdXIsA==,type:str]
    SECRET_VPN_CITY: ENC[AES256_GCM,data:aQG3jI18VT4=,iv:+JIwKMA232RsmfHFX4265uByFTvxbD53/mjc2tvtoDw=,tag:V6pjXZ9yyWXELqJla4wQng==,type:str]
    EMAIL_PASS: ENC[AES256_GCM,data:VOU78Yw3JpWBX3X/C5U38w==,iv:b16b40JJcSO6xwjuXiISve+eG9lcx3tVQDTAeU+7rgQ=,tag:S1wR60ZBUMe0XVcy1gyTbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWFUzaWdFMkJBS0Q0bHVu
            ZTVKOVl0dDI3YXVvYVpGa1RGUHJxRHZWdnlVCnNFRGpXOGNrdlBBVlRGd1FqWk9I
            ODZCbmRpOTVkanZxWjFiSm1rNXg1dlEKLS0tIE51bE9rV1ltTlhyK09aUGV2NXpT
            bDZ2UnVYTkxsaktwbWo1VjZDYkY5Uk0KkdXnV2/IJYKoXI86v1d8jiVQXxW/VlLt
            TEpexL9U0mGhBARgv73g0mXfbcNsNOo+PZE9IerAKPcbsUgjmJOkLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-12T10:06:21Z"
    mac: ENC[AES256_GCM,data:RToELCl5MJTk7BxMwlreGtf23A9MVVGEkxGzwnUmCqbtBYG6y9c164TeGULvjxyfbczwJDI2V+1KXsBjpxx43N9MnRU8PyMIzG/6Onretb6NqZ6/WPIcwBuaVc8Ng51KNcLOnpvIVdMcCSStNQn5NBus+BnEbxbqZGSyYRwiltU=,iv:DXD+a2aZqOLxdsvLPu2RdeUcBAGzIN2RouWJhulEc1E=,tag:mN0D+TZqXbTNgL9QAmEyrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
