apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:fymLbFd8KCvKJHtpzoH/NVML9nkSEZb/e9YUGRqq0OPbsXoQilzOSFudYZrwv7ExFTqdcT1kDaousznUBdh5PlpAOAfx2d7ge7kl4gB8rkHFws7GHcrBgTPzvsZ9kg==,iv:uMbsl1xbpV4pQkWHZvoKDhh8fMhkMY2Ib+wWKVHCTEo=,tag:2ClOMho5W1v9KKImKkr/sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIL1EwYU40ZlU5QTBEVU5t
            b0xtQmp6dHZMc0JmeVhkN0xqd3NLRTdyTTM4ClpyM1hiNmhZOFZ5OUhnNitGMTVi
            NjZzK295OHpDV3ErQXhyUEk2UGRuUG8KLS0tIE94WVVSMG1SWUVINHJpcWFENkNq
            dkZoNjJsWTNtd21jN1RjSW5QZmVBcm8KY+OaWtjPfk9qUtbT6ZyfQYCBaTDw53Oy
            oBybsYf0CSnyrjzvBpPPt4zgs/3MRiRKPuHjuBvoP6JvWgeXVa3vEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T18:50:53Z"
    mac: ENC[AES256_GCM,data:rrMxGwbXiy91xOoFs/JZsaXuFaxL/rdnTgEe73d0D/KMWRoMYx/sc+BISm/dTVYuz65uUClqPxM46TnR3QKAM0bDZKnuoOivkGM2CKl45glVHrdwOUPYKD88BEPb8ehMwL15koeeEeo7NnFoPjJgtFoCnJO5DogFP5xF/PKWLMM=,iv:4qU0E+Rh/CjnTF1SxxIIR6xkdjbqcIyJ8b5VsYOtUjA=,tag:nR26cAppQSkhPH+uSWMFaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
