---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./../../../../templates/volsync
  - ./externalsecrets.yaml
  - ./pvc.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: plex-loki-rules
    files:
      - plex.yaml=./resources/lokirule.yaml
    options:
      labels:
        loki_rule: "true"
generatorOptions:
  disableNameSuffixHash: true
