---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: docker.io/1password/connect-api
              tag: 1.7.2
            env:
              - name: OP_BUS_PORT
                value: "11220"
              - name: OP_BUS_PEERS
                value: "localhost:11221"
              - name: OP_HTTP_PORT
                value: &port 8080
              - name: OP_SESSION
                valueFrom:
                  secretKeyRef:
                    name: onepassword-connect-secret
                    key: 1password-credentials.json

            resources:
              requests:
                cpu: 5m
                memory: 10Mi
              limits:
                memory: 100Mi

            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /heartbeat
                    port: *port
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 15
              startup:
                enabled: false

          sync:
            image:
              repository: docker.io/1password/connect-sync
              tag: 1.7.2
            env:
              - name: OP_HTTP_PORT
                value: &port2 8081
              - name: OP_BUS_PORT
                value: "11221"
              - name: OP_BUS_PEERS
                value: "localhost:11220"
              - name: OP_SESSION
                valueFrom:
                  secretKeyRef:
                    name: onepassword-connect-secret
                    key: 1password-credentials.json
            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port2
                  initialDelaySeconds: 15
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /heartbeat
                    port: *port2
                  failureThreshold: 3
                  periodSeconds: 30
                  initialDelaySeconds: 15


    service:
      app:
        controller: app
        ports:
          http:
            port: *port

    persistence:
      shared:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /home/opuser/.op/data
