---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app longhorn
  namespace: storage
spec:
  releaseName: *app
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.6.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:

    defaultSettings:
      defaultReplicaCount: 3
      snapshotMaxCount: 2
      # Below requires that nodes used for storage have the label
      # node.longhorn.io/create-default-disk=true
      createDefaultDiskLabeledNodes: false
      storageOverProvisioningPercentage: 150
      storageMinimalAvailablePercentage: 50
      guaranteedEngineManagerCPU: 20
      guaranteedReplicaManagerCPU: 20
      defaultDataPath: /var/lib/longhorn
      restoreVolumeRecurringJobs: false
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      defaultLonghornStaticStorageClass: longhorn

    ingress:
      enabled: true
      ingressClassName: internal
      host: longhorn.${SECRET_DOMAIN}
      tls: true
      tlsSecret: longhorn.local-tls

  valuesFrom:
    - kind: Secret
      name: *app
      valuesKey: NAS_BACKUP
      targetPath: defaultSettings.backupTarget
