---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_KEY }}"
        AUTHENTIK_URL: "{{ .authentik_url }}"
        POSTGRES_DB: &dbname authentik
        POSTGRES_HOST: &dbhost "{{ .authentik_postgres_host }}"
        POSTGRES_USER: &dbuser "{{ .authentik_postgres_user }}"
        POSTGRES_PASS: &dbpass "{{ .authentik_postgres_pass }}"
        REDIS_PASS: "{{ .REDIS_PASSWORD }}"
        SMTP_PORT: "{{ .EMAIL_PORT }}"
        SMTP_USERNAME: "{{ .EMAIL_USERNAME }}"
        SMTP_PASS: "{{ .EMAIL_PASS }}"
        SMTP_FROM: "{{ .authentik_email_username }}"
        SMTP_HOST: "{{ .EMAIL_HOST }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .pgpassword }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: cloudnative-pg
    - extract:
        key: email-info
