---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-authentik-redis-master-0
  namespace: auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn-database
