---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name cloudflared-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials.json: |
          {
            "AccountTag": "{{ .CLOUDFLARED_ACCOUNT_TAG }}",
            "TunnelSecret": "{{ .CLOUDFLARED_TUNNEL_SECRET }}",
            "TunnelID": "{{ .TUNNEL_ID }}"
          }
        TUNNEL_ID: "{{ .TUNNEL_ID }}"
  dataFrom:
    - extract:
        key: cloudflare
