
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-secrets
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: github-webhook-token-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Bazarr postgres variables
        token: "{{ .webhook_token }}"
  dataFrom:
    - extract:
        key: flux
