apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:G27dfNH6RbEWzXdudZAktThUn2ApWVy3aBSgFki88y0=,iv:ayFBh7TvewskuqTVRhr8o3xVZitm921UsIsPRJeBMlk=,tag:e7OVJ9dVjdFYulZjDEYyug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZHRoQjZkLzdTRHNMWTRv
            T3g0S2s2WDZIWmpCSjZpT0djWFdINDVWL1ZvCkZjVXhETVNGSDZnVFcwRDV6b1JU
            aVZBNU11WC9MTGI1Y2N5NlVVOC96UTgKLS0tIG0zSkNaZXJOK2pLU0hOY2dINnA5
            WUgxR3hLNGtkWkM3K2NySGhlZDR2QVUKhnTC2j7ja5iyaVWn82RsswnVJWNePRth
            I1QJqPTlFILlOVsLvcNF0A5kRJ0buywEMjSvYYykvj3pPK3AWdadcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T19:03:12Z"
    mac: ENC[AES256_GCM,data:24FNSlw1tqhggzR1Cz8JbfOG9o4wHux8aQyjcyiKkgtlbUu41vi19/t2LOKC0Rwy6lRdMmim/8xYsCW+2daTf6eXF9KFZ5Ii/Cjp+8+XQU8cf0qetORqdTkwFmDabdIiG9+/Iteen0cw0q9K8ilik6IFq8Mm9ptjq6Qo2y8vctc=,iv:2VAD7t4Y3s0fw66HoYGYs8ycWpZfMTO/evmMpMsZ74s=,tag:g33FhApiId8BBrBd54mrDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
