---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app jellyfin-test
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: intel-device-plugins-gpu
  path: ./kubernetes/apps/media/jellyfin/test
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  wait: false
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 300Gi
      VOLSYNC_CACHE_CAPACITY: 20Gi
      VOLSYNC_SCHEDULE: "45 * * * *"
