---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name adguard-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ADGUARD_URL: "{{ .adguard_url }}"
        ADGUARD_USER: "{{ .adguard_user }}"
        ADGUARD_PASSWORD: "{{ .adguard_password }}"
  dataFrom:
    - extract:
        key: adguard
