---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name lidarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LIDARR__API_KEY: "{{ .lidarr_api_key }}"
        LIDARR__POSTGRES_HOST: &dbHost "{{ .postgres_db_host }}"
        LIDARR__POSTGRES_PORT: "5432"
        LIDARR__POSTGRES_USER: &dbUser "{{ .lidarr_db_user }}"
        LIDARR__POSTGRES_PASSWORD: &dbPass "{{ .lidarr_db_pass }}"
        LIDARR__POSTGRES_MAIN_DB: lidarr_main
        LIDARR__POSTGRES_LOG_DB: lidarr_log
        INIT_POSTGRES_DBNAME: lidarr_main lidarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .pgpassword }}"
        NAS1_ADDR: "{{ .nas1_addr }}"
        NAS2_ADDR: "{{ .nas2_addr }}"
        NAS3_ADDR: "{{ .nas3_addr }}"
  dataFrom:
    - extract:
        key: nas-info
    - extract:
        key: cloudnative-pg
    - extract:
        key: lidarr
