---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lidarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  dependsOn:
    - name: cloudnative-pg
      namespace: database
  uninstall:
    keepHistory: false

  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 65539

    controllers:
      lidarr:

        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: *app

        containers:
          lidarr:
            image:
              repository: ghcr.io/onedr0p/lidarr-develop
              tag: 2.5.0.4277@sha256:dcc8ed7213f037e0f97c8117fe0e7703dbc47b211d04bf949b6ac8aa6b7b31a0
            envFrom: *envFrom

    service:
      lidarr:
        controller: lidarr
        ports:
          http:
            port: 8686

    ingress:
      lidarr:
        enabled: false
        className: "nginx"
        hosts:
          - host: &host lidarr.${INTERNAL_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: lidarr
                  port: http
        tls:
          - hosts:
              - *host
            secretName: lidarr.tls

    persistence:
      media:
        type: nfs
        path: /volume1/Media/Music
        globalMounts:
          - path: /media

      temp:
        type: nfs
        path: /volume1/temp
        globalMounts:
          - path: /temp_dir


  valuesFrom:
    - kind: Secret
      name: *app
      valuesKey: NAS1_ADDR
      targetPath: persistence.media.server

    - kind: Secret
      name: *app
      valuesKey: NAS1_ADDR
      targetPath: persistence.temp.server
